Configure widget permissions using ModuleRunner.instance.invoke
matrix-org/matrix-react-sdk-module-api pull request #11
Opened 2023-02-09 09:43 UTC by maheichyk

This PR suggests changes to module API to support customization of widget permissions using `ModuleRunner.instance.invoke` as discussed here: https://github.com/matrix-org/matrix-react-sdk-module-api/pull/9#issuecomment-1420552769

2023-02-09 10:08 UTC, richvdh commented
@andybalaam it looks like you've already done a bunch of thinking about this, so I'm afraid I'm going to throw it over the wall in your direction!

2023-02-14 20:12 UTC, maheichyk commented
Hi @andybalaam could you please provide feedback on this PR?

2023-02-15 10:46 UTC, andybalaam commented
> Hi @andybalaam could you please provide feedback on this PR?

@maheichyk I'm sorry for the delay on this. I will take a look today.

2023-02-15 15:50 UTC, andybalaam commented
@maheichyk this looks great. Please could we have a small test similar to what you did in https://github.com/matrix-org/matrix-react-sdk-module-api/pull/9 and then we'll be ready to merge this.

Thanks again for your work on this and your patience.

2023-02-15 15:51 UTC, andybalaam requested changes
Looks good - requesting a test that validates the flow.

2023-02-15 18:08 UTC, maheichyk commented
@andybalaam thanks for the feedback! Test was added, please have a look.

2023-02-15 20:29 UTC, maheichyk commented
If test is fine, would be great maybe to have a new version of `matrix-react-sdk-module-api` that can be used to build this PR https://github.com/matrix-org/matrix-react-sdk/pull/10121

2023-02-16 10:29 UTC, andybalaam approved these changes
This looks great, thank you!

2023-02-16 10:29 UTC, merged

2023-02-16 10:37 UTC, andybalaam commented
@maheichyk new release 0.0.4 published at https://www.npmjs.com/package/@matrix-org/react-sdk-module-api